site_name: "PHongo"
repo_url: https://github.com/10gen-labs/mongo-php-driver-prototype
theme: spacelab
pages:
    - [index.md, Home]
    - [batch.md, Batch CRUD]
    - [commands.md, Running Commands]
    - [crud.md, CRUD]
extra_javascript:
    - pretty.js
    - jira.js
